name: Trigger auto deployment for azure-python-experiment-10

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/azure-python-experiment-10-AutoDeployTrigger-48bae78d-53ed-4bec-b4dd-c4901ce8a85d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREPYTHONEXPERIMENT10_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZUREPYTHONEXPERIMENT10_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZUREPYTHONEXPERIMENT10_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: helloworldshomik2026.azurecr.io
          registryUsername: ${{ secrets.AZUREPYTHONEXPERIMENT10_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZUREPYTHONEXPERIMENT10_REGISTRY_PASSWORD }}
          containerAppName: azure-python-experiment-10
          resourceGroup: Practice-RG
          imageToBuild: helloworldshomik2026.azurecr.io/azure-python-experiment-10:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


